const courses = document.querySelector('.courses')

courses.addEventListener("click", () => {
    courses.style.backgroundColor = '#F5F5F5'
    courses.style.color = 'orange'
    blog.style.backgroundColor = 'white'
    blog.style.color = 'black'
    page.style.backgroundColor = 'white'
    page.style.color = 'black'
    add.style.backgroundColor = 'white'
    add.style.color = 'black'
    theme.style.backgroundColor = 'white'
    theme.style.color = 'black'
    home.style.backgroundColor = 'white'
    home.style.color = 'black'
})
const blog = document.querySelector('.blog')
blog.addEventListener("click", () => {
    blog.style.backgroundColor = '#F5F5F5'
    blog.style.color = 'orange'
    courses.style.backgroundColor = 'white'
    courses.style.color = 'black'
    page.style.backgroundColor = 'white'
    page.style.color = 'black'
    add.style.backgroundColor = 'white'
    add.style.color = 'black'
    theme.style.backgroundColor = 'white'
    theme.style.color = 'black'
    home.style.backgroundColor = 'white'
    home.style.color = 'black'
})
const page = document.querySelector('.page')
page.addEventListener("click", () => {
    page.style.backgroundColor = '#F5F5F5'
    page.style.color = 'orange'
    blog.style.backgroundColor = 'white'
    blog.style.color = 'black'
    courses.style.backgroundColor = 'white'
    courses.style.color = 'black'
    add.style.backgroundColor = 'white'
    add.style.color = 'black'
    theme.style.backgroundColor = 'white'
    theme.style.color = 'black'
    home.style.backgroundColor = 'white'
    home.style.color = 'black'
})
const add = document.querySelector('.add')
add.addEventListener("click", () => {
    add.style.backgroundColor = '#F5F5F5)'
    add.style.color = 'orange'
    blog.style.backgroundColor = 'white'
    blog.style.color = 'black'
    courses.style.backgroundColor = 'white'
    courses.style.color = 'black'
    page.style.backgroundColor = 'white'
    page.style.color = 'black'
    theme.style.backgroundColor = 'white'
    theme.style.color = 'black'
    home.style.backgroundColor = 'white'
    home.style.color = 'black'
})
const theme = document.querySelector('.theme')
theme.addEventListener("click", () => {
    theme.style.backgroundColor = '#F5F5F5'
    theme.style.color = 'orange'
    blog.style.backgroundColor = 'white'
    blog.style.color = 'black'
    courses.style.backgroundColor = 'white'
    courses.style.color = 'black'
    add.style.backgroundColor = 'white'
    add.style.color = 'black'
    page.style.backgroundColor = 'white'
    page.style.color = 'black'
    home.style.backgroundColor = 'white'
    home.style.color = 'black'
})
const home = document.querySelector('.home')
home.addEventListener("click", () => {
    home.style.backgroundColor = '#F5F5F5'
    home.style.color = 'orange'
    theme.style.backgroundColor = 'white'
    theme.style.color = 'black'
    blog.style.backgroundColor = 'white'
    blog.style.color = 'black'
    courses.style.backgroundColor = 'white'
    courses.style.color = 'black'
    add.style.backgroundColor = 'white'
    add.style.color = 'black'
    page.style.backgroundColor = 'white'
    page.style.color = 'black'
})
const main_content = document.querySelector('.main_content')
const content_course_over = document.querySelector('.content_course_over')
const content_blog_left = document.querySelector('.content_blog_left')
const line_contact = document.querySelector('.line_contact')
const login = document.querySelector('.login')
const content_login = document.querySelector('.content_login')

courses.addEventListener("click", () => {
    content_course_over.style.display = 'block'
    main_content.style.display = 'none'
    content_blog_left.style.display = 'none'
    line_contact.style.display = 'none'
    content_login.style.display = 'none'
})
home.addEventListener("click", () => {
    main_content.style.display = 'block'
    content_course_over.style.display = 'none'
    content_blog_left.style.display = 'none'
    line_contact.style.display = 'none'
    content_login.style.display = 'none'
})
blog.addEventListener("click", () => {
    main_content.style.display = 'none'
    content_course_over.style.display = 'none'
    content_blog_left.style.display = 'block'
    line_contact.style.display = 'none'
    content_login.style.display = 'none'
})
page.addEventListener("click", () => {
    line_contact.style.display = 'flex'
    main_content.style.display = 'none'
    content_course_over.style.display = 'none'
    content_blog_left.style.display = 'none'
    content_login.style.display = 'none'
})
login.addEventListener("click", () => {
    line_contact.style.display = 'none'
    main_content.style.display = 'none'
    content_course_over.style.display = 'none'
    content_blog_left.style.display = 'none'
    content_login.style.display = 'flex'
    courses.style.backgroundColor = 'white'
    courses.style.color = 'black'
    blog.style.backgroundColor = 'white'
    blog.style.color = 'black'
    page.style.backgroundColor = 'white'
    page.style.color = 'black'
    add.style.backgroundColor = 'white'
    add.style.color = 'black'
    theme.style.backgroundColor = 'white'
    theme.style.color = 'black'
    home.style.backgroundColor = 'white'
    home.style.color = 'black'

})
const course_ins = document.querySelector('.Instructor')
const course_over = document.querySelector('.Overview')
const course_cur = document.querySelector('.Curriculum')
const course_FAQs = document.querySelector('.FAQs')
const course_reviews = document.querySelector('.Reviews')
const LearnPress_course_ins = document.querySelector('.LearnPress_course_ins')
const LearnPress_course_over = document.querySelector('.LearnPress_course_over')
const LearnPress_course_cur = document.querySelector('.LearnPress_course_cur')
const LearnPress_course_FAQs = document.querySelector('.LearnPress_course_FAQs')
const LearnPress_course_reviews = document.querySelector('.LearnPress_course_reviews')
course_ins.addEventListener("click", () => {
    LearnPress_course_over.style.display = 'none'
    LearnPress_course_ins.style.display = 'flex'
    LearnPress_course_cur.style.display = 'none'
    LearnPress_course_FAQs.style.display = 'none'
    LearnPress_course_reviews.style.display = 'none'
    course_over.style.backgroundColor = 'white'
    course_ins.style.backgroundColor = '#F5F5F5'
    course_cur.style.backgroundColor = 'white'
    course_FAQs.style.backgroundColor = 'white'
    course_reviews.style.backgroundColor = 'white'
    course_over.style.color = 'black'
    course_ins.style.color = 'orange'
    course_cur.style.color = 'black'
    course_FAQs.style.color = 'black'
    course_reviews.style.color = 'black'
})
course_over.addEventListener("click", () => {
    LearnPress_course_ins.style.display = 'none'
    LearnPress_course_over.style.display = 'flex'
    LearnPress_course_cur.style.display = 'none'
    LearnPress_course_FAQs.style.display = 'none'
    LearnPress_course_reviews.style.display = 'none'
    course_ins.style.backgroundColor = 'white'
    course_over.style.backgroundColor = '#F5F5F5'
    course_cur.style.backgroundColor = 'white'
    course_FAQs.style.backgroundColor = 'white'
    course_reviews.style.backgroundColor = 'white'
    course_ins.style.color = 'black'
    course_over.style.color = 'orange'
    course_cur.style.color = 'black'
    course_FAQs.style.color = 'black'
    course_reviews.style.color = 'black'
})
course_cur.addEventListener("click", () => {
    LearnPress_course_over.style.display = 'none'
    LearnPress_course_ins.style.display = 'none'
    LearnPress_course_cur.style.display = 'flex'
    LearnPress_course_FAQs.style.display = 'none'
    LearnPress_course_reviews.style.display = 'none'
    course_over.style.backgroundColor = 'white'
    course_ins.style.backgroundColor = 'white'
    course_cur.style.backgroundColor = '#F5F5F5'
    course_FAQs.style.backgroundColor = 'white'
    course_reviews.style.backgroundColor = 'white'
    course_over.style.color = 'black'
    course_ins.style.color = 'black'
    course_cur.style.color = 'orange'
    course_FAQs.style.color = 'black'
    course_reviews.style.color = 'black'
})
course_FAQs.addEventListener("click", () => {
    LearnPress_course_over.style.display = 'none'
    LearnPress_course_ins.style.display = 'none'
    LearnPress_course_cur.style.display = 'none'
    LearnPress_course_FAQs.style.display = 'flex'
    LearnPress_course_reviews.style.display = 'none'
    course_over.style.backgroundColor = 'white'
    course_ins.style.backgroundColor = 'white'
    course_cur.style.backgroundColor = 'white'
    course_FAQs.style.backgroundColor = '#F5F5F5'
    course_reviews.style.backgroundColor = 'white'
    course_over.style.color = 'black'
    course_ins.style.color = 'black'
    course_cur.style.color = 'black'
    course_FAQs.style.color = 'orange'
    course_reviews.style.color = 'black'
})
course_reviews.addEventListener("click", () => {
    LearnPress_course_over.style.display = 'none'
    LearnPress_course_ins.style.display = 'none'
    LearnPress_course_cur.style.display = 'none'
    LearnPress_course_FAQs.style.display = 'none'
    LearnPress_course_reviews.style.display = 'flex'
    course_over.style.backgroundColor = 'white'
    course_ins.style.backgroundColor = 'white'
    course_cur.style.backgroundColor = 'white'
    course_FAQs.style.backgroundColor = 'white'
    course_reviews.style.backgroundColor = '#F5F5F5'
    course_over.style.color = 'black'
    course_ins.style.color = 'black'
    course_cur.style.color = 'black'
    course_FAQs.style.color = 'black'
    course_reviews.style.color = 'orange'
})
const content_left = document.querySelector('.content_left')
const BackGround_content_left = document.querySelector('.BackGround_content_left')
const vector4 = document.querySelector('.vector4')
const vector6 = document.querySelector('.vector6')

vector4.addEventListener("click", () => {
    content_left.style.display = 'none'
    BackGround_content_left.style.display = 'flex'
})
vector6.addEventListener("click", () => {
    content_left.style.display = 'flex'
    BackGround_content_left.style.display = 'none'
})
const word = document.querySelector('.word_p')
const content_blog = document.querySelector('.content_left_a')
word.addEventListener("click", () => {
    content_left.style.display = 'none'
    BackGround_content_left.style.display = 'none'
    content_blog.style.display = 'flex'
})
blog.addEventListener("click", () => {
    content_left.style.display = 'flex'
    BackGround_content_left.style.display = 'none'
    content_blog.style.display = 'none'
})
const Page_one = document.querySelector('.Page_one')
const Page_one_1 = document.querySelector('.Page_one_1')
const Page_two = document.querySelector('.Page_two')
const Page_three = document.querySelector('.Page_three')
const Laura1 = document.querySelector('.Laura1')
const Laura2 = document.querySelector('.Laura2')
const left = document.querySelector('.left')
const right = document.querySelector('.right')
Page_one.addEventListener("click", () => {
    Laura1.style.display = 'flex'
    Laura2.style.display = 'none'
    Page_two.style.backgroundColor = '#F5F5F5'
    Page_two.style.color = 'black'
    Page_one.style.backgroundColor = 'black'
    Page_one.style.color = 'white'
    Page_three.style.backgroundColor = '#F5F5F5'
    Page_three.style.color = 'black'
})
Page_two.addEventListener("click", () => {
    Laura1.style.display = 'none'
    Laura2.style.display = 'flex'
    Page_two.style.backgroundColor = 'black'
    Page_two.style.color = 'white'
    Page_one.style.display = 'none'
    Page_one_1.style.display = 'flex'
    Page_three.style.backgroundColor = '#F5F5F5'
    Page_three.style.color = 'black'
})
Page_three.addEventListener("click", () => {
    Laura1.style.display = 'none'
    Laura2.style.display = 'none'
    Page_two.style.backgroundColor = '#F5F5F5'
    Page_two.style.color = 'black'
    Page_one.style.backgroundColor = '#F5F5F5'
    Page_one.style.color = 'black'
    Page_three.style.backgroundColor = 'black'
    Page_three.style.color = 'white'
})
Page_one_1.addEventListener("click", () => {
    Laura1.style.display = 'flex'
    Laura2.style.display = 'none'
    Page_two.style.backgroundColor = '#F5F5F5'
    Page_two.style.color = 'black'
    Page_one.style.display = 'flex'
    Page_one_1.style.display = 'none'
    Page_one.style.backgroundColor = 'black'
    Page_one.style.color = 'white'
    Page_three.style.backgroundColor = '#F5F5F5'
    Page_three.style.color = 'black'
})
const post = document.querySelector('.post button')
console.log(post.innerHTML)
post.addEventListener("click", () => {
    window.alert("dang ky thanh cong");
})